### ISSUE TITLE
Confusion about feature importance in the non-linear case

### ISSUE THREAD

**Issue by Silflame** [juntang-zhuang/explain_invertible#1]
A very interesting job! But I have a question that in the None-linear case of section 3.3.3 in your paper "Decision Explanation and Feature Importance for Invertible Networks", do x and x_p mean the corresponding paired data (x and its projection) in Equation 10? Or x is sampled around x_p?

**Comment by juntang-zhuang** [comment]
Thanks for your interest. x_p is the projection of x, x is from the dataset, not sampled around x_p.

**Comment by Silflame** [comment]
Thanks for your answer.  Does the distance between x and it projection x_p have to be very small to satisfy Taylor's expansion? Meanwhile, we could get f(x), f(x_p) and (x - x_p) in Equation 10, but can these varibales guarantee that we can solve for the first-order derivative of f(x_p)?

**Comment by juntang-zhuang** [comment]
For Taylor expansion to be meaningful, x_p and x has to be close. 
You can directly feed x_p to the network and perform backward to get the gradient. This is guaranteed.
